# TEST YOUR SKILLS

In [ ]:
import pandas as pd

In [ ]:
#Load a CSV file named sales_data.csv into a pandas DataFrame. Display the first 5 rows of the DataFrame.

In [1]:
#Filter the DataFrame to show only the rows where the Sales column is greater than 500.
#Display the filtered DataFrame.

In [2]:
#Filter the DataFrame to show only the rows where the Region is 'North' and the Sales are greater than 700.
#Display the filtered DataFrame.

In [3]:
#Select the Product, Sales, and Region columns from the DataFrame and display them.

In [4]:
#Add a new column named SalesTax which is 10% of the Sales column.
#Display the first 5 rows of the DataFrame with the new column.

In [5]:
#Create a new column named HighSales that contains True if the Sales value is greater than 800 and False otherwise.
#Display the first 5 rows of the DataFrame with the new column.

In [6]:
# Filter the DataFrame to show only the rows where the HighSales column is True.
# Display the filtered DataFrame.

In [7]:
# Add two new columns: Discount which is 5% of Sales, and FinalPrice which is Sales minus Discount.
# Display the first 5 rows of the DataFrame with the new columns.

In [8]:
#Filter the DataFrame to show only the rows where the SalesTax is greater than 50 and FinalPrice is less than 800.
# Display the filtered DataFrame.

In [ ]:
# Filter the DataFrame to show only the rows where the Region is 'South' and Sales are between 600 and 1000 (inclusive).
# Display the filtered DataFrame.