In [2]:
#Handling Inappropriate Data
#Usually this step is executed when dealing with EXTERNAL DATASET
#The only thing that will help you deal with Inappropriate data is HAVING ENOUGH DOMAIN KNOWLEDGE

In [ ]:
#Guidelines by Prashant Nair
# ================================================================================================
#
# 1. Identify the type of data for each column (Numerical, Categorical,Ordinal, PureString)
# 2. Check and remove all Duplicate Records from the dataframe
# 3. Check and remove all Duplicate Columns from the dataframe
# 4. If your column is Numerical Column, perform the following:
#
#                 - If dealing with Continuous ND, check w.r.t domain whether the following parameter is achieved:
#                              1. Positive Numbers are allowed or not
#                              2. Negative Numbers are allowed or not
#                              3. Decimals are allowed or just Integers expected
#
#                    If any of the above is not allowed, DELETE that COLUMN ENTRY
#
#
#                 - If dealing with Discrete ND, check w.r.t domain whether the following parameter is achieved:
#                              1. Positive Numbers are allowed or not
#                              2. Negative Numbers are allowed or not
#                              3. Decimals are allowed or just Integers expected
#                              4. Check whether the number falls in a specified range as defined by the domain.
#
#                    If any of the above is not allowed, DELETE that COLUMN ENTRY
#
#
#5. If the columns are CATEGORICAL column, perform the following:
#                - Get the unique values of the column
#                - HANDLEE the data that has SPELLING ERRORS,CASE ERRORS. Ensure Case is Unified!
#                - Check whether the groups/categories showin in unique values match the domain spec.
#
#                if any unusual category found, DELETE that SPECIFIC RECORD
#
#6. If the columns are ORDINAL column, perform the following:
#                - Get the unique values of the column
#                - HANDLEE the data that has SPELLING ERRORS,CASE ERRORS. Ensure Case is Unified!
#                - Check whether the groups/categories showin in unique values match the domain spec.
#                - Check the rank of each unique column and ensure it matches the domain spec.
#
#                if any unusual category/rank found, DELETE that SPECIFIC RECORD
#
# 7. Dealing with String Column ---------------------------- Dont Touch the column :) (NLP tasks)

In [3]:
import pandas as pd
import numpy as np

In [16]:
data = pd.read_csv('datasetExample.csv')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       11 non-null     int64
 1   Age_Group        11 non-null     object
 2   Rating(1-5)      11 non-null     int64
 3   Hotel            11 non-null     object
 4   FoodPreference   11 non-null     object
 5   Bill             11 non-null     int64
 6   NoOfPax          11 non-null     int64
 7   EstimatedSalary  11 non-null     int64
 8   Age_Group.1      11 non-null     object
dtypes: int64(5), object(4)
memory usage: 924.0+ bytes

In [6]:
data.head()

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+

In [ ]:
# 1. Identify the type of data for each column (Numerical, Categorical,Ordinal, PureString)
 #   Column           Non-Null Count  Dtype
#---  ------           --------------  -----
# 0   CustomerID       11 non-null     int64  -----------> Numerical  (Continuous)
# 1   Age_Group        11 non-null     object -----------> Categorical
# 2   Rating(1-5)      11 non-null     int64  -----------> Numerical  (Discrete Range is 1 to 5 (integer))
# 3   Hotel            11 non-null     object -----------> Categorical
# 4   FoodPreference   11 non-null     object -----------> Categorical
# 5   Bill             11 non-null     int64  -----------> Numerical  (Continuous)
# 6   NoOfPax          11 non-null     int64  -----------> Numerical  (Discrete --- Domain Expert informed me that the range for pax is 1-20)
# 7   EstimatedSalary  11 non-null     int64  -----------> Numerical  (Continuous)
# 8   Age_Group.1      11 non-null     object -----------> Categorical

In [17]:
# 2. Check and remove all Duplicate Records from the dataframe
#
# In pandas, we can detect and remove duplicate records using drop_duplicates

data.drop_duplicates(ignore_index=True, inplace=True)

In [12]:
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary,Age_Group.1
0,1,20-25,4,Ibis,veg,1300,2,40000,20-25
1,2,30-35,5,LemonTree,Non-Veg,2000,3,59000,30-35
2,3,25-30,6,RedFox,Veg,1322,2,30000,25-30
3,4,20-25,-1,LemonTree,Veg,1234,2,120000,20-25
4,5,35+,3,Ibis,Vegetarian,989,2,45000,35+
5,6,35+,3,Ibys,Non-Veg,1909,2,122220,35+
6,7,35+,4,RedFox,Vegetarian,1000,-1,21122,35+
7,8,20-25,7,LemonTree,Veg,2999,-10,345673,20-25
8,9,25-30,2,Ibis,Non-Veg,3456,3,-99999,25-30
9,10,30-35,5,RedFox,non-Veg,-6755,4,87777,30-35

In [13]:
# 3. Check and remove all Duplicate Columns from the dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       10 non-null     int64
 1   Age_Group        10 non-null     object
 2   Rating(1-5)      10 non-null     int64
 3   Hotel            10 non-null     object
 4   FoodPreference   10 non-null     object
 5   Bill             10 non-null     int64
 6   NoOfPax          10 non-null     int64
 7   EstimatedSalary  10 non-null     int64
 8   Age_Group.1      10 non-null     object
dtypes: int64(5), object(4)
memory usage: 852.0+ bytes

In [21]:
data.drop(columns=['Age_Group.1'] , inplace=True)

In [20]:
#uniqueRecords = data [ data['Age_Group'] != data['Age_Group.1'] ]
#uniqueRecords

Empty DataFrame
Columns: [CustomerID, Age_Group, Rating(1-5), Hotel, FoodPreference, Bill, NoOfPax, EstimatedSalary, Age_Group.1]
Index: []

In [ ]:
# 4. If your column is Numerical Column, perform the following:
#
#                 - If dealing with Continuous ND, check w.r.t domain whether the following parameter is achieved:
#                              1. Positive Numbers are allowed or not
#                              2. Negative Numbers are allowed or not
#                              3. Decimals are allowed or just Integers expected
#
#                    If any of the above is not allowed, DELETE that COLUMN ENTRY
#
 #   Column           Non-Null Count  Dtype
#---  ------           --------------  -----
# 0   CustomerID       11 non-null     int64  -----------> Numerical  (Continuous) ---> +ve allowed, -ve not allowed , integers
# 5   Bill             11 non-null     int64  -----------> Numerical  (Continuous) ---> +ve allowed, -ve not allowed, integers and float
# 7   EstimatedSalary  11 non-null     int64  -----------> Numerical  (Continuous) ---> +ve allowed, -ve not allowed, integers

In [25]:
#Bill
#Simply replace value with null (np.nan)

data['Bill'].loc[  data['Bill'] < 0  ] = np.nan

<ipython-input-25-3b8ce3f5b591>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Bill'].loc[  data['Bill'] < 0  ] = np.nan

In [26]:
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4,Ibis,veg,1300.0,2,40000
1,2,30-35,5,LemonTree,Non-Veg,2000.0,3,59000
2,3,25-30,6,RedFox,Veg,1322.0,2,30000
3,4,20-25,-1,LemonTree,Veg,1234.0,2,120000
4,5,35+,3,Ibis,Vegetarian,989.0,2,45000
5,6,35+,3,Ibys,Non-Veg,1909.0,2,122220
6,7,35+,4,RedFox,Vegetarian,1000.0,-1,21122
7,8,20-25,7,LemonTree,Veg,2999.0,-10,345673
8,9,25-30,2,Ibis,Non-Veg,3456.0,3,-99999
9,10,30-35,5,RedFox,non-Veg,NaN,4,87777

In [27]:
# CustomerID and EstimatedSalary handling (assignment)

In [ ]:
#                 - If dealing with Discrete ND, check w.r.t domain whether the following parameter is achieved:
#                              1. Positive Numbers are allowed or not
#                              2. Negative Numbers are allowed or not
#                              3. Decimals are allowed or just Integers expected
#                              4. Check whether the number falls in a specified range as defined by the domain.
#
#                    If any of the above is not allowed, DELETE that COLUMN ENTRY
#

#   Column           Non-Null Count  Dtype
#---  ------           --------------  -----
# 2   Rating(1-5)      11 non-null     int64  -----------> Numerical  +ve allowd,-ve not allowd, int, (Discrete Range is 1 to 5 (integer))
# 6   NoOfPax          11 non-null     int64  -----------> Numerical  +ve allowd,-ve not allowd, int,(Discrete --- Domain Expert informed me that the range for pax is 1-20)

In [30]:
#Rating

data['Rating(1-5)'].loc[( data['Rating(1-5)'] < 1 ) | (data['Rating(1-5)'] > 5)] = np.nan

<ipython-input-30-36f65592a20a>:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data['Rating(1-5)'].loc[( data['Rating(1-5)'] < 1 ) | (data['Rating(1-5)'] > 5)] = np.nan
<ipython-input-30-36f65592a20a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Rating(1-5)'].loc[( data['Rating(1-5)'] < 1 ) | (data['Rating(1-5)'] > 5)] = np.nan

In [31]:
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4.0,Ibis,veg,1300.0,2,40000
1,2,30-35,5.0,LemonTree,Non-Veg,2000.0,3,59000
2,3,25-30,NaN,RedFox,Veg,1322.0,2,30000
3,4,20-25,NaN,LemonTree,Veg,1234.0,2,120000
4,5,35+,3.0,Ibis,Vegetarian,989.0,2,45000
5,6,35+,3.0,Ibys,Non-Veg,1909.0,2,122220
6,7,35+,4.0,RedFox,Vegetarian,1000.0,-1,21122
7,8,20-25,NaN,LemonTree,Veg,2999.0,-10,345673
8,9,25-30,2.0,Ibis,Non-Veg,3456.0,3,-99999
9,10,30-35,5.0,RedFox,non-Veg,NaN,4,87777

In [ ]:
# # 6   NoOfPax  (assignment)

In [ ]:
#5. If the columns are CATEGORICAL column, perform the following:
#                - Get the unique values of the column
#                - HANDLEE the data that has SPELLING ERRORS,CASE ERRORS. Ensure Case is Unified!
#                - Check whether the groups/categories showin in unique values match the domain spec.
#
#                if any unusual category found, DELETE that SPECIFIC RECORD

 #   Column           Non-Null Count  Dtype
#---  ------           --------------  -----
# 1   Age_Group        11 non-null     object -----------> Categorical
# 3   Hotel            11 non-null     object -----------> Categorical
# 4   FoodPreference   11 non-null     object -----------> Categorical

In [32]:
#Hotel
data['Hotel'].unique()

array(['Ibis', 'LemonTree', 'RedFox', 'Ibys'], dtype=object)

In [35]:
#Lets assume domain expert says, Ibys is a spelling mistake. The correct spelling is Ibis.
#Pandas ----> replace

data['Hotel'].replace(['Ibys','ibis'],'Ibis' , inplace=True)

In [36]:
data

,CustomerID,Age_Group,Rating(1-5),Hotel,FoodPreference,Bill,NoOfPax,EstimatedSalary
0,1,20-25,4.0,Ibis,veg,1300.0,2,40000
1,2,30-35,5.0,LemonTree,Non-Veg,2000.0,3,59000
2,3,25-30,NaN,RedFox,Veg,1322.0,2,30000
3,4,20-25,NaN,LemonTree,Veg,1234.0,2,120000
4,5,35+,3.0,Ibis,Vegetarian,989.0,2,45000
5,6,35+,3.0,Ibis,Non-Veg,1909.0,2,122220
6,7,35+,4.0,RedFox,Vegetarian,1000.0,-1,21122
7,8,20-25,NaN,LemonTree,Veg,2999.0,-10,345673
8,9,25-30,2.0,Ibis,Non-Veg,3456.0,3,-99999
9,10,30-35,5.0,RedFox,non-Veg,NaN,4,87777

In [37]:
#Food Preference, agegroup assignment

In [39]:
?data.replace